name: Go CI
on:
  push:
    branches: [chapter13]
jobs:
  build:
    name: Build
    strategy:
      matrix:
        go-version: [1.23.x, 1.22.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Check out code
        uses: actions/checkout@v4
      - name: Test
        run: |
          cd go
          go test -v ./...
